<script setup>
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Plus, Search, Edit, Delete } from '@element-plus/icons-vue'
import { adminApi } from '../../api/blog'

const data=ref({records:[],total:0}),categories=ref([]),tags=ref([]),loading=ref(false),saving=ref(false),drawer=ref(false)
const query=reactive({page:1,size:10,keyword:'',status:''})
const emptyForm=()=>({id:null,title:'',slug:'',summary:'',content:'',coverUrl:'',categoryId:null,status:'DRAFT',isTop:0,tagIds:[]})
const form=reactive(emptyForm())
async function load(){loading.value=true;try{data.value=await adminApi.articles(query)}catch(e){ElMessage.error(e.message)}finally{loading.value=false}}
async function open(row){Object.assign(form,emptyForm());if(row){try{Object.assign(form,await adminApi.article(row.id));form.tagIds=(form.tags||[]).map(t=>t.id)}catch(e){return ElMessage.error(e.message)}}else form.categoryId=categories.value[0]?.id;drawer.value=true}
async function save(){if(!form.title||!form.slug||!form.content||!form.categoryId)return ElMessage.warning('请填写标题、别名、分类和正文');saving.value=true;try{await adminApi.saveArticle(form.id,{...form});ElMessage.success(form.id?'文章已更新':'文章已创建');drawer.value=false;load()}catch(e){ElMessage.error(e.message)}finally{saving.value=false}}
async function remove(row){try{await ElMessageBox.confirm(`删除文章「${row.title}」？该操作会进行逻辑删除。`,'删除确认',{type:'warning'});await adminApi.deleteArticle(row.id);ElMessage.success('文章已删除');load()}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(e.message)}}
function search(){query.page=1;load()}
onMounted(async()=>{try{[categories.value,tags.value]=await Promise.all([adminApi.categories(),adminApi.tags()])}catch(e){ElMessage.error(e.message)}load()})
</script>

<template>
  <section class="admin-panel"><div class="panel-toolbar"><el-form inline @submit.prevent="search"><el-form-item><el-input v-model="query.keyword" clearable placeholder="搜索文章标题" :prefix-icon="Search" @clear="search"/></el-form-item><el-form-item><el-select v-model="query.status" clearable placeholder="全部状态" style="width:130px"><el-option label="已发布" value="PUBLISHED"/><el-option label="草稿" value="DRAFT"/></el-select></el-form-item><el-button @click="search">查询</el-button></el-form><el-button type="primary" :icon="Plus" @click="open()">新增文章</el-button></div>
    <el-table v-loading="loading" :data="data.records" row-key="id"><el-table-column label="文章" min-width="300"><template #default="{row}"><div class="article-cell"><div class="mini-cover">{{row.title?.slice(0,1)}}</div><div><strong>{{row.title}}</strong><small>{{row.slug}}</small></div></div></template></el-table-column><el-table-column prop="categoryName" label="分类" width="120"/><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="row.status==='PUBLISHED'?'success':'info'" effect="light">{{row.status==='PUBLISHED'?'已发布':'草稿'}}</el-tag></template></el-table-column><el-table-column prop="viewCount" label="阅读" width="90"/><el-table-column prop="publishedAt" label="发布时间" width="170"><template #default="{row}">{{row.publishedAt?.replace('T',' ').slice(0,16)||'—'}}</template></el-table-column><el-table-column label="操作" width="140" fixed="right"><template #default="{row}"><el-button link type="primary" :icon="Edit" @click="open(row)">编辑</el-button><el-button link type="danger" :icon="Delete" @click="remove(row)">删除</el-button></template></el-table-column></el-table>
    <div class="table-pagination"><span>共 {{data.total}} 篇文章</span><el-pagination v-model:current-page="query.page" :page-size="query.size" :total="data.total" layout="prev,pager,next" @current-change="load"/></div>
  </section>
  <el-drawer v-model="drawer" :title="form.id?'编辑文章':'新增文章'" size="min(760px, 92%)" destroy-on-close><el-form label-position="top"><div class="form-grid"><el-form-item label="文章标题" required><el-input v-model="form.title" maxlength="200"/></el-form-item><el-form-item label="URL 别名" required><el-input v-model="form.slug" placeholder="example-article-slug"/></el-form-item></div><el-form-item label="摘要"><el-input v-model="form.summary" type="textarea" :rows="3" maxlength="500" show-word-limit/></el-form-item><div class="form-grid"><el-form-item label="文章分类" required><el-select v-model="form.categoryId" style="width:100%"><el-option v-for="item in categories" :key="item.id" :label="item.name" :value="item.id"/></el-select></el-form-item><el-form-item label="标签"><el-select v-model="form.tagIds" multiple clearable style="width:100%"><el-option v-for="tag in tags" :key="tag.id" :label="tag.name" :value="tag.id"/></el-select></el-form-item></div><el-form-item label="封面图片 URL"><el-input v-model="form.coverUrl"/></el-form-item><el-form-item label="Markdown 正文" required><el-input v-model="form.content" type="textarea" :rows="16" placeholder="# 从这里开始写作…"/></el-form-item><div class="form-grid"><el-form-item label="发布状态"><el-radio-group v-model="form.status"><el-radio value="DRAFT">保存草稿</el-radio><el-radio value="PUBLISHED">立即发布</el-radio></el-radio-group></el-form-item><el-form-item label="文章设置"><el-switch v-model="form.isTop" :active-value="1" :inactive-value="0" active-text="置顶文章"/></el-form-item></div></el-form><template #footer><el-button @click="drawer=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存文章</el-button></template></el-drawer>
</template>
