<script setup>
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Search } from '@element-plus/icons-vue'
import { adminApi } from '../../api/blog'
import { useAuthStore } from '../../store/auth'

const auth=useAuthStore(),data=ref({records:[],total:0}),loading=ref(false),available=ref(true),query=reactive({page:1,size:10,keyword:''})
async function load(){loading.value=true;try{data.value=await adminApi.users(query);available.value=true}catch{available.value=false;data.value={records:[],total:0}}finally{loading.value=false}}
async function changeRole(row,role){if(row.id===auth.user?.id)return ElMessage.warning('不能修改当前登录账号的权限');try{await ElMessageBox.confirm(`确认将 ${row.nickname||row.username} 的角色修改为 ${role==='ADMIN'?'管理员':'普通用户'}？`,'权限变更',{type:'warning'});await adminApi.updateUserRole(row.id,role);ElMessage.success('权限已更新');load()}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(e.message)}}
async function changeStatus(row){const disabling=row.status==='ACTIVE',next=disabling?'DISABLED':'ACTIVE';if(row.id===auth.user?.id&&disabling)return ElMessage.warning('不能禁用当前登录账号');try{await ElMessageBox.confirm(`确认${disabling?'禁用':'启用'}用户 ${row.nickname||row.username}？${disabling?'禁用后该用户将立即无法登录或进行互动。':''}`,`${disabling?'禁用':'启用'}用户`,{type:disabling?'warning':'info'});await adminApi.updateUserStatus(row.id,next);ElMessage.success(`用户已${disabling?'禁用':'启用'}`);load()}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(e.message)}}
onMounted(load)
</script>

<template><section class="admin-panel"><el-alert v-if="!available" title="用户数据加载失败，请检查后端服务。" type="error" show-icon :closable="false" class="panel-alert"/><div class="panel-toolbar"><el-form inline @submit.prevent="query.page=1;load()"><el-form-item><el-input v-model="query.keyword" clearable placeholder="搜索用户名或昵称" :prefix-icon="Search"/></el-form-item><el-button @click="query.page=1;load()">查询</el-button></el-form><span class="table-count">共 {{data.total}} 位用户</span></div><el-table v-loading="loading" :data="data.records" row-key="id"><el-table-column label="用户" min-width="220"><template #default="{row}"><div class="user-cell"><el-avatar :src="row.avatar">{{row.nickname?.slice(0,1)||row.username?.slice(0,1)}}</el-avatar><div><strong>{{row.nickname}}</strong><small>@{{row.username}}</small></div></div></template></el-table-column><el-table-column prop="email" label="邮箱" min-width="200"/><el-table-column label="角色" width="150"><template #default="{row}"><el-select :model-value="row.role" :disabled="row.id===auth.user?.id" @change="role=>changeRole(row,role)"><el-option label="普通用户" value="USER"/><el-option label="管理员" value="ADMIN"/></el-select></template></el-table-column><el-table-column label="状态" width="110"><template #default="{row}"><el-tag :type="row.status==='ACTIVE'?'success':'danger'">{{row.status==='ACTIVE'?'正常':'已禁用'}}</el-tag></template></el-table-column><el-table-column prop="createdAt" label="注册时间" width="170"><template #default="{row}">{{row.createdAt?.replace('T',' ').slice(0,16)}}</template></el-table-column><el-table-column label="账号操作" width="110" fixed="right"><template #default="{row}"><el-button link :type="row.status==='ACTIVE'?'danger':'success'" :disabled="row.id===auth.user?.id" @click="changeStatus(row)">{{row.status==='ACTIVE'?'禁用':'启用'}}</el-button></template></el-table-column></el-table><div class="table-pagination"><span></span><el-pagination v-model:current-page="query.page" :page-size="query.size" :total="data.total" layout="prev,pager,next" @current-change="load"/></div></section></template>
